clc;  
 clear all;  
 disp('___________________________________________');  

 n=input('Mencari Bulan Ke =');  
 if n==1;  
   disp('___________________________');  
 elseif n==2;  
   disp(['2 = Bulan Februari ']);  
     disp('___________________________');  
 elseif n==3;  
   disp(['3 = Bulan Maret ']);  
   disp('___________________________');  
 elseif n==4;  
   disp(['4 = Bulan April ']);  
     disp('___________________________');  
   elseif n==5;  
   disp(['5 = Bulan Mai ']);  
     disp('___________________________');  
   elseif n==6;  
   disp(['6 = Bulan Juni ']);  
     disp('___________________________');  
   elseif n==7;  
   disp(['7 = Bulan Juli ']);  
     disp('___________________________');  
   elseif n==8;  
   disp(['8 = Bulan Agustus ']);  
     disp('___________________________');  
   elseif n==9;  
   disp(['9 = Bulan September ']);  
     disp('___________________________');  
   elseif n==10;  
   disp(['10 = Bulan Oktober ']);  
     disp('___________________________');  
   elseif n==11;  
   disp(['11 = Bulan November ']);  
     disp('___________________________');  
   else n==12;  
   disp(['12 = Bulan Desember ']);  
     disp('___________________________');  
end  